package xyz.yychainsaw.portfolio.content.persistence;

enum ProjectTable {
    PROJECT_TRANSLATION,
    PROJECT_TAG,
    PROJECT_SKILL,
    PROJECT_MEDIA,
    CONTENT_BLOCK,
    CONTENT_BLOCK_TRANSLATION,
    BLOCK_MEDIA,
    BLOCK_MARKDOWN_TRANSLATION,
    BLOCK_VIDEO,
    BLOCK_CODE,
    BLOCK_QUOTE_TRANSLATION,
    BLOCK_ACTION,
    BLOCK_METRIC,
    BLOCK_METRIC_TRANSLATION
}
