package xyz.yychainsaw.portfolio.content.persistence;

enum SiteTable {
    PROFILE_TRANSLATION,
    SEO_TRANSLATION,
    ACCESSIBILITY_TRANSLATION,
    NAVIGATION,
    NAVIGATION_TRANSLATION,
    HERO,
    HERO_TRANSLATION,
    HERO_MEDIA,
    ABOUT_TRANSLATION,
    WORK_TRANSLATION,
    CONTACT_TRANSLATION,
    PRIVACY_TRANSLATION,
    SOCIAL_LINK,
    PROFILE_FACT,
    PROFILE_FACT_TRANSLATION,
    PROFILE_SKILL,
    PROFILE_SKILL_TRANSLATION,
    ROADMAP_HEADER_TRANSLATION,
    ROADMAP_STAGE,
    ROADMAP_STAGE_TRANSLATION,
    ROADMAP_OUTCOME,
    ROADMAP_OUTCOME_TRANSLATION,
    RESUME_DOCUMENT
}
