CREATE ROLE portfolio_runtime_access
    NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE test_migrator
    LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
    PASSWORD 'migrator_test_password';
CREATE ROLE test_runtime
    LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
    PASSWORD 'runtime_test_password';
GRANT portfolio_runtime_access TO test_runtime WITH INHERIT TRUE, SET FALSE;
REVOKE CONNECT, CREATE, TEMPORARY ON DATABASE portfolio_test FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE portfolio_test TO test_migrator, test_runtime;
GRANT CREATE ON DATABASE portfolio_test TO test_migrator;
CREATE SCHEMA portfolio AUTHORIZATION test_migrator;
GRANT USAGE ON SCHEMA portfolio TO portfolio_runtime_access WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator
    GRANT SELECT, REFERENCES ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator
    GRANT SELECT ON TABLES TO portfolio_runtime_access;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator IN SCHEMA portfolio
    GRANT INSERT ON TABLES TO portfolio_runtime_access;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator IN SCHEMA portfolio
    GRANT INSERT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator
    GRANT EXECUTE ON FUNCTIONS TO portfolio_runtime_access;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator IN SCHEMA portfolio
    GRANT EXECUTE ON FUNCTIONS TO portfolio_runtime_access;
ALTER DEFAULT PRIVILEGES FOR ROLE test_migrator IN SCHEMA portfolio
    GRANT EXECUTE ON FUNCTIONS TO PUBLIC;
ALTER ROLE test_migrator SET search_path TO portfolio, public;
ALTER ROLE test_runtime SET search_path TO portfolio, public;
